/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardDashLayoutImport } from './routes/dashboard/_dashLayout'
import { Route as DashboardDashLayoutIndexImport } from './routes/dashboard/_dashLayout/index'
import { Route as DashboardDashLayoutRegisteredUsersImport } from './routes/dashboard/_dashLayout/registered-users'
import { Route as DashboardDashLayoutPatientUsersImport } from './routes/dashboard/_dashLayout/patient-users'
import { Route as DashboardDashLayoutNewsManagementImport } from './routes/dashboard/_dashLayout/news-management'
import { Route as DashboardDashLayoutDoctorsDetailsImport } from './routes/dashboard/_dashLayout/doctors-details'
import { Route as DashboardDashLayoutDoctorsAvailabilityImport } from './routes/dashboard/_dashLayout/doctors-availability'
import { Route as DashboardDashLayoutDashboardUsersImport } from './routes/dashboard/_dashLayout/dashboard-users'
import { Route as DashboardDashLayoutAppointmentsImport } from './routes/dashboard/_dashLayout/appointments'
import { Route as DashboardDashLayoutAppointmentRatingsImport } from './routes/dashboard/_dashLayout/appointment-ratings'
import { Route as DashboardDashLayoutAccountImport } from './routes/dashboard/_dashLayout/account'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashLayoutRoute = DashboardDashLayoutImport.update({
  id: '/_dashLayout',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDashLayoutIndexRoute = DashboardDashLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashLayoutRoute,
} as any)

const DashboardDashLayoutRegisteredUsersRoute =
  DashboardDashLayoutRegisteredUsersImport.update({
    id: '/registered-users',
    path: '/registered-users',
    getParentRoute: () => DashboardDashLayoutRoute,
  } as any)

const DashboardDashLayoutPatientUsersRoute =
  DashboardDashLayoutPatientUsersImport.update({
    id: '/patient-users',
    path: '/patient-users',
    getParentRoute: () => DashboardDashLayoutRoute,
  } as any)

const DashboardDashLayoutNewsManagementRoute =
  DashboardDashLayoutNewsManagementImport.update({
    id: '/news-management',
    path: '/news-management',
    getParentRoute: () => DashboardDashLayoutRoute,
  } as any)

const DashboardDashLayoutDoctorsDetailsRoute =
  DashboardDashLayoutDoctorsDetailsImport.update({
    id: '/doctors-details',
    path: '/doctors-details',
    getParentRoute: () => DashboardDashLayoutRoute,
  } as any)

const DashboardDashLayoutDoctorsAvailabilityRoute =
  DashboardDashLayoutDoctorsAvailabilityImport.update({
    id: '/doctors-availability',
    path: '/doctors-availability',
    getParentRoute: () => DashboardDashLayoutRoute,
  } as any)

const DashboardDashLayoutDashboardUsersRoute =
  DashboardDashLayoutDashboardUsersImport.update({
    id: '/dashboard-users',
    path: '/dashboard-users',
    getParentRoute: () => DashboardDashLayoutRoute,
  } as any)

const DashboardDashLayoutAppointmentsRoute =
  DashboardDashLayoutAppointmentsImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => DashboardDashLayoutRoute,
  } as any)

const DashboardDashLayoutAppointmentRatingsRoute =
  DashboardDashLayoutAppointmentRatingsImport.update({
    id: '/appointment-ratings',
    path: '/appointment-ratings',
    getParentRoute: () => DashboardDashLayoutRoute,
  } as any)

const DashboardDashLayoutAccountRoute = DashboardDashLayoutAccountImport.update(
  {
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardDashLayoutRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_dashLayout': {
      id: '/dashboard/_dashLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_dashLayout/account': {
      id: '/dashboard/_dashLayout/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardDashLayoutAccountImport
      parentRoute: typeof DashboardDashLayoutImport
    }
    '/dashboard/_dashLayout/appointment-ratings': {
      id: '/dashboard/_dashLayout/appointment-ratings'
      path: '/appointment-ratings'
      fullPath: '/dashboard/appointment-ratings'
      preLoaderRoute: typeof DashboardDashLayoutAppointmentRatingsImport
      parentRoute: typeof DashboardDashLayoutImport
    }
    '/dashboard/_dashLayout/appointments': {
      id: '/dashboard/_dashLayout/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardDashLayoutAppointmentsImport
      parentRoute: typeof DashboardDashLayoutImport
    }
    '/dashboard/_dashLayout/dashboard-users': {
      id: '/dashboard/_dashLayout/dashboard-users'
      path: '/dashboard-users'
      fullPath: '/dashboard/dashboard-users'
      preLoaderRoute: typeof DashboardDashLayoutDashboardUsersImport
      parentRoute: typeof DashboardDashLayoutImport
    }
    '/dashboard/_dashLayout/doctors-availability': {
      id: '/dashboard/_dashLayout/doctors-availability'
      path: '/doctors-availability'
      fullPath: '/dashboard/doctors-availability'
      preLoaderRoute: typeof DashboardDashLayoutDoctorsAvailabilityImport
      parentRoute: typeof DashboardDashLayoutImport
    }
    '/dashboard/_dashLayout/doctors-details': {
      id: '/dashboard/_dashLayout/doctors-details'
      path: '/doctors-details'
      fullPath: '/dashboard/doctors-details'
      preLoaderRoute: typeof DashboardDashLayoutDoctorsDetailsImport
      parentRoute: typeof DashboardDashLayoutImport
    }
    '/dashboard/_dashLayout/news-management': {
      id: '/dashboard/_dashLayout/news-management'
      path: '/news-management'
      fullPath: '/dashboard/news-management'
      preLoaderRoute: typeof DashboardDashLayoutNewsManagementImport
      parentRoute: typeof DashboardDashLayoutImport
    }
    '/dashboard/_dashLayout/patient-users': {
      id: '/dashboard/_dashLayout/patient-users'
      path: '/patient-users'
      fullPath: '/dashboard/patient-users'
      preLoaderRoute: typeof DashboardDashLayoutPatientUsersImport
      parentRoute: typeof DashboardDashLayoutImport
    }
    '/dashboard/_dashLayout/registered-users': {
      id: '/dashboard/_dashLayout/registered-users'
      path: '/registered-users'
      fullPath: '/dashboard/registered-users'
      preLoaderRoute: typeof DashboardDashLayoutRegisteredUsersImport
      parentRoute: typeof DashboardDashLayoutImport
    }
    '/dashboard/_dashLayout/': {
      id: '/dashboard/_dashLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashLayoutIndexImport
      parentRoute: typeof DashboardDashLayoutImport
    }
  }
}

// Create and export the route tree

interface DashboardDashLayoutRouteChildren {
  DashboardDashLayoutAccountRoute: typeof DashboardDashLayoutAccountRoute
  DashboardDashLayoutAppointmentRatingsRoute: typeof DashboardDashLayoutAppointmentRatingsRoute
  DashboardDashLayoutAppointmentsRoute: typeof DashboardDashLayoutAppointmentsRoute
  DashboardDashLayoutDashboardUsersRoute: typeof DashboardDashLayoutDashboardUsersRoute
  DashboardDashLayoutDoctorsAvailabilityRoute: typeof DashboardDashLayoutDoctorsAvailabilityRoute
  DashboardDashLayoutDoctorsDetailsRoute: typeof DashboardDashLayoutDoctorsDetailsRoute
  DashboardDashLayoutNewsManagementRoute: typeof DashboardDashLayoutNewsManagementRoute
  DashboardDashLayoutPatientUsersRoute: typeof DashboardDashLayoutPatientUsersRoute
  DashboardDashLayoutRegisteredUsersRoute: typeof DashboardDashLayoutRegisteredUsersRoute
  DashboardDashLayoutIndexRoute: typeof DashboardDashLayoutIndexRoute
}

const DashboardDashLayoutRouteChildren: DashboardDashLayoutRouteChildren = {
  DashboardDashLayoutAccountRoute: DashboardDashLayoutAccountRoute,
  DashboardDashLayoutAppointmentRatingsRoute:
    DashboardDashLayoutAppointmentRatingsRoute,
  DashboardDashLayoutAppointmentsRoute: DashboardDashLayoutAppointmentsRoute,
  DashboardDashLayoutDashboardUsersRoute:
    DashboardDashLayoutDashboardUsersRoute,
  DashboardDashLayoutDoctorsAvailabilityRoute:
    DashboardDashLayoutDoctorsAvailabilityRoute,
  DashboardDashLayoutDoctorsDetailsRoute:
    DashboardDashLayoutDoctorsDetailsRoute,
  DashboardDashLayoutNewsManagementRoute:
    DashboardDashLayoutNewsManagementRoute,
  DashboardDashLayoutPatientUsersRoute: DashboardDashLayoutPatientUsersRoute,
  DashboardDashLayoutRegisteredUsersRoute:
    DashboardDashLayoutRegisteredUsersRoute,
  DashboardDashLayoutIndexRoute: DashboardDashLayoutIndexRoute,
}

const DashboardDashLayoutRouteWithChildren =
  DashboardDashLayoutRoute._addFileChildren(DashboardDashLayoutRouteChildren)

interface DashboardRouteChildren {
  DashboardDashLayoutRoute: typeof DashboardDashLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashLayoutRoute: DashboardDashLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashLayoutRouteWithChildren
  '/dashboard/account': typeof DashboardDashLayoutAccountRoute
  '/dashboard/appointment-ratings': typeof DashboardDashLayoutAppointmentRatingsRoute
  '/dashboard/appointments': typeof DashboardDashLayoutAppointmentsRoute
  '/dashboard/dashboard-users': typeof DashboardDashLayoutDashboardUsersRoute
  '/dashboard/doctors-availability': typeof DashboardDashLayoutDoctorsAvailabilityRoute
  '/dashboard/doctors-details': typeof DashboardDashLayoutDoctorsDetailsRoute
  '/dashboard/news-management': typeof DashboardDashLayoutNewsManagementRoute
  '/dashboard/patient-users': typeof DashboardDashLayoutPatientUsersRoute
  '/dashboard/registered-users': typeof DashboardDashLayoutRegisteredUsersRoute
  '/dashboard/': typeof DashboardDashLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashLayoutIndexRoute
  '/dashboard/account': typeof DashboardDashLayoutAccountRoute
  '/dashboard/appointment-ratings': typeof DashboardDashLayoutAppointmentRatingsRoute
  '/dashboard/appointments': typeof DashboardDashLayoutAppointmentsRoute
  '/dashboard/dashboard-users': typeof DashboardDashLayoutDashboardUsersRoute
  '/dashboard/doctors-availability': typeof DashboardDashLayoutDoctorsAvailabilityRoute
  '/dashboard/doctors-details': typeof DashboardDashLayoutDoctorsDetailsRoute
  '/dashboard/news-management': typeof DashboardDashLayoutNewsManagementRoute
  '/dashboard/patient-users': typeof DashboardDashLayoutPatientUsersRoute
  '/dashboard/registered-users': typeof DashboardDashLayoutRegisteredUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_dashLayout': typeof DashboardDashLayoutRouteWithChildren
  '/dashboard/_dashLayout/account': typeof DashboardDashLayoutAccountRoute
  '/dashboard/_dashLayout/appointment-ratings': typeof DashboardDashLayoutAppointmentRatingsRoute
  '/dashboard/_dashLayout/appointments': typeof DashboardDashLayoutAppointmentsRoute
  '/dashboard/_dashLayout/dashboard-users': typeof DashboardDashLayoutDashboardUsersRoute
  '/dashboard/_dashLayout/doctors-availability': typeof DashboardDashLayoutDoctorsAvailabilityRoute
  '/dashboard/_dashLayout/doctors-details': typeof DashboardDashLayoutDoctorsDetailsRoute
  '/dashboard/_dashLayout/news-management': typeof DashboardDashLayoutNewsManagementRoute
  '/dashboard/_dashLayout/patient-users': typeof DashboardDashLayoutPatientUsersRoute
  '/dashboard/_dashLayout/registered-users': typeof DashboardDashLayoutRegisteredUsersRoute
  '/dashboard/_dashLayout/': typeof DashboardDashLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/appointment-ratings'
    | '/dashboard/appointments'
    | '/dashboard/dashboard-users'
    | '/dashboard/doctors-availability'
    | '/dashboard/doctors-details'
    | '/dashboard/news-management'
    | '/dashboard/patient-users'
    | '/dashboard/registered-users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/appointment-ratings'
    | '/dashboard/appointments'
    | '/dashboard/dashboard-users'
    | '/dashboard/doctors-availability'
    | '/dashboard/doctors-details'
    | '/dashboard/news-management'
    | '/dashboard/patient-users'
    | '/dashboard/registered-users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/_dashLayout'
    | '/dashboard/_dashLayout/account'
    | '/dashboard/_dashLayout/appointment-ratings'
    | '/dashboard/_dashLayout/appointments'
    | '/dashboard/_dashLayout/dashboard-users'
    | '/dashboard/_dashLayout/doctors-availability'
    | '/dashboard/_dashLayout/doctors-details'
    | '/dashboard/_dashLayout/news-management'
    | '/dashboard/_dashLayout/patient-users'
    | '/dashboard/_dashLayout/registered-users'
    | '/dashboard/_dashLayout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_dashLayout"
      ]
    },
    "/dashboard/_dashLayout": {
      "filePath": "dashboard/_dashLayout.jsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_dashLayout/account",
        "/dashboard/_dashLayout/appointment-ratings",
        "/dashboard/_dashLayout/appointments",
        "/dashboard/_dashLayout/dashboard-users",
        "/dashboard/_dashLayout/doctors-availability",
        "/dashboard/_dashLayout/doctors-details",
        "/dashboard/_dashLayout/news-management",
        "/dashboard/_dashLayout/patient-users",
        "/dashboard/_dashLayout/registered-users",
        "/dashboard/_dashLayout/"
      ]
    },
    "/dashboard/_dashLayout/account": {
      "filePath": "dashboard/_dashLayout/account.jsx",
      "parent": "/dashboard/_dashLayout"
    },
    "/dashboard/_dashLayout/appointment-ratings": {
      "filePath": "dashboard/_dashLayout/appointment-ratings.jsx",
      "parent": "/dashboard/_dashLayout"
    },
    "/dashboard/_dashLayout/appointments": {
      "filePath": "dashboard/_dashLayout/appointments.jsx",
      "parent": "/dashboard/_dashLayout"
    },
    "/dashboard/_dashLayout/dashboard-users": {
      "filePath": "dashboard/_dashLayout/dashboard-users.jsx",
      "parent": "/dashboard/_dashLayout"
    },
    "/dashboard/_dashLayout/doctors-availability": {
      "filePath": "dashboard/_dashLayout/doctors-availability.jsx",
      "parent": "/dashboard/_dashLayout"
    },
    "/dashboard/_dashLayout/doctors-details": {
      "filePath": "dashboard/_dashLayout/doctors-details.jsx",
      "parent": "/dashboard/_dashLayout"
    },
    "/dashboard/_dashLayout/news-management": {
      "filePath": "dashboard/_dashLayout/news-management.jsx",
      "parent": "/dashboard/_dashLayout"
    },
    "/dashboard/_dashLayout/patient-users": {
      "filePath": "dashboard/_dashLayout/patient-users.jsx",
      "parent": "/dashboard/_dashLayout"
    },
    "/dashboard/_dashLayout/registered-users": {
      "filePath": "dashboard/_dashLayout/registered-users.jsx",
      "parent": "/dashboard/_dashLayout"
    },
    "/dashboard/_dashLayout/": {
      "filePath": "dashboard/_dashLayout/index.jsx",
      "parent": "/dashboard/_dashLayout"
    }
  }
}
ROUTE_MANIFEST_END */
